### ISSUE TITLE
Hi I couldn't install this package.

### ISSUE THREAD

**Issue by pokkur** [dan-gamble/postcss-font-awesome#8]
I expect a response from you.

``` debug.log
1476 verbose stack Error: postcss-font-awesome@0.3.3 postinstall: `node ./generateIconConfig.js`
1476 verbose stack Exit status 1
1476 verbose stack     at EventEmitter.<anonymous> (/Users/USERNAME/.nodebrew/node/v6.3.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
1476 verbose stack     at emitTwo (events.js:106:13)
1476 verbose stack     at EventEmitter.emit (events.js:191:7)
1476 verbose stack     at ChildProcess.<anonymous> (/Users/USERNAME/.nodebrew/node/v6.3.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
1476 verbose stack     at emitTwo (events.js:106:13)
1476 verbose stack     at ChildProcess.emit (events.js:191:7)
1476 verbose stack     at maybeClose (internal/child_process.js:852:16)
1476 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
1477 verbose pkgid postcss-font-awesome@0.3.3
1478 verbose cwd /Users/USERNAME/projects/PROJECTNAME
1479 error Darwin 14.5.0
1480 error argv "/Users/USERNAME/.nodebrew/node/v6.3.0/bin/node" "/Users/USERNAME/.nodebrew/current/bin/npm" "i" "-D" "postcss-font-awesome"
1481 error node v6.3.0
1482 error npm  v3.10.3
1483 error code ELIFECYCLE
1484 error postcss-font-awesome@0.3.3 postinstall: `node ./generateIconConfig.js`
1484 error Exit status 1
1485 error Failed at the postcss-font-awesome@0.3.3 postinstall script 'node ./generateIconConfig.js'.
1485 error Make sure you have the latest version of node.js and npm installed.
1485 error If you do, this is most likely a problem with the postcss-font-awesome package,
1485 error not with npm itself.
1485 error Tell the author that this fails on your system:
1485 error     node ./generateIconConfig.js
1485 error You can get information on how to open an issue for this project with:
1485 error     npm bugs postcss-font-awesome
1485 error Or if that isn't available, you can get their info via:
1485 error     npm owner ls postcss-font-awesome
1485 error There is likely additional logging output above.
1486 verbose exit [ 1, true ]
```

**Comment by dan-gamble** [comment]
I just tested the installation myself and it worked fine for me so kind of hard to debug.

What operating system are you using?

**Comment by pokkur** [comment]
Thank you for reply.
OS X 10.10.5

**Comment by dan-gamble** [comment]
@pokkur Is this still occurring for you? Was it a one off or is it everytime you try and use it? Sorry for the late reply i didn't get an email for this

**Comment by pokkur** [comment]
@dan-gamble The problem is still not resolved. But I'll try a different machine. Thnak you.

**Comment by dan-gamble** [comment]
Lemme know if that helps, i've no idea what could be a blocker sorry. You use the same node as me as well

**Comment by corysimmons** [comment]
Fix: Use a recent version of Node.
